"""Downloadable prediction report (CSV + PDF). Pure-python PDF via fpdf2 —
no wkhtmltopdf/Chromium dependency, which matters for a one-command deploy.
"""
from __future__ import annotations

import io
from datetime import datetime

import pandas as pd
from fpdf import FPDF


def build_csv_report(result: dict, source: str) -> bytes:
    row = {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "input_source": source,
        "predicted_class": result["predicted_class"],
        "probability_malignant": round(result["probability_malignant"], 4),
    }
    return pd.DataFrame([row]).to_csv(index=False).encode("utf-8")


class _ReportPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(13, 115, 119)
        self.cell(0, 10, "CellScan - Prediction Report", ln=True)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(90, 90, 90)
        self.cell(0, 6, f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
        self.ln(4)


def build_pdf_report(result: dict, source: str, top_contributors: list[dict] | None = None) -> bytes:
    pdf = _ReportPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(11, 31, 42)
    pdf.cell(0, 8, f"Input source: {source}", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(20, 51, 87)
    pdf.cell(0, 12, f"{result['predicted_class']}  ({result['probability_malignant']*100:.1f}% malignancy probability)", ln=True)
    pdf.ln(4)

    if top_contributors:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(11, 31, 42)
        pdf.cell(0, 8, "Top contributing features (SHAP)", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for row in top_contributors:
            direction = "raises" if row["shap_value"] > 0 else "lowers"
            pdf.cell(0, 6, f"  - {row['feature']}: value={row['value']:.3f} ({direction} malignancy score)", ln=True)
        pdf.ln(4)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 90, 20)
    pdf.multi_cell(
        0, 5,
        "Research/educational use only. This report was generated by a machine learning "
        "research prototype and is not a validated diagnostic device. It must not be used "
        "for real clinical decision-making. Consult a licensed pathologist and radiologist "
        "for an actual diagnosis.",
    )

    return bytes(pdf.output(dest="S"))
